### ISSUE TITLE
WebGoat dont see WebWolf on custom port

### ISSUE THREAD

**Issue by Jihadist** [WebGoat/WebGoat#513]
If i run webgoat for example on 65080 and webwolf on 65090 webgoat will not see webwolf so i couldnt send email and catch error 
> There was an error while sending the e-mail. Is WebWolf running?
> 404 Not Found

How can i provide webwolf custom port to webgoat? Thanx

**Comment by nbaars** [comment]
@Jihadist you need to pass an environment variable when starting WebGoat, for example you can take a look at the `docker-compose.yml`:

```
version: '2.1'

services:
  webgoat:
    image: webgoat/webgoat-8.0
    environment:
      - WEBWOLF_HOST=webwolf
      - WEBWOLF_PORT=9090
```

If you use the jar you can pass the environments with `-DWEBWOLF_PORT=....` etc.
Hope this help with running it on a different port, if not please reopen this issue.
